version: "3.8"

services:
  backend:
    container_name: backend
    init: true
    build: ../
    env_file:
      - ../.env
    environment:
      # Override the value of host because in this case, the name of the host would be 'db' as it as named.
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - auth-api_data:/var/lib/postgresql/data

volumes:
  auth-api_data:
