services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - auth-api_data:/var/lib/postgresql/data

volumes:
  auth-api_data:
