# .github/workflows/ci.yml

# CI Workflow
name: ci

# This workflow is expected to run whenever the commited code is pushed or PR is raised to the Master branch!
on:
  push:
    branches:
      - Dev

# This job is expected to run whenever the above condition is fulfilled!
jobs:
  dockerhub:
    name: Build, push to DockerHub

    # This job is required to run on ubuntu!
    runs-on: ubuntu-latest

    # Following are the steps which will be performed to complete this job!
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        env:
          DOCKERHUB_REPO: busycaesar/auth-api
          SHA_TAG: sha-${{github.sha}}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{env.DOCKERHUB_REPO}}:beta,
            ${{env.DOCKERHUB_REPO}}:${{env.SHA_TAG}}
